//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 12:36:51 下午 CST 
//


package com.raise.generator;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenModel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GenModel">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MultiFile"/>
 *     &lt;enumeration value="SingleFile"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GenModel")
@XmlEnum
public enum GenModel {


    /**
     * 产生多个文件,这个时候需要填写扩展名属性
     * 
     */
    @XmlEnumValue("MultiFile")
    MULTI_FILE("MultiFile"),

    /**
     * 产生一个文件,这个时候需要填写文件名称
     * 
     */
    @XmlEnumValue("SingleFile")
    SINGLE_FILE("SingleFile");
    private final String value;

    GenModel(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GenModel fromValue(String v) {
        for (GenModel c: GenModel.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
