//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 12:36:51 ÏÂÎç CST 
//


package com.raise.generator;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Config.Variables.Variable }
     * 
     */
    public Config.Variables.Variable createConfigVariablesVariable() {
        return new Config.Variables.Variable();
    }

    /**
     * Create an instance of {@link Config.Files.File }
     * 
     */
    public Config.Files.File createConfigFilesFile() {
        return new Config.Files.File();
    }

    /**
     * Create an instance of {@link Config.Table.Subtable.Variable }
     * 
     */
    public Config.Table.Subtable.Variable createConfigTableSubtableVariable() {
        return new Config.Table.Subtable.Variable();
    }

    /**
     * Create an instance of {@link Config.GenAll.File }
     * 
     */
    public Config.GenAll.File createConfigGenAllFile() {
        return new Config.GenAll.File();
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link Config.GenAll.File.Variable }
     * 
     */
    public Config.GenAll.File.Variable createConfigGenAllFileVariable() {
        return new Config.GenAll.File.Variable();
    }

    /**
     * Create an instance of {@link Config.Table }
     * 
     */
    public Config.Table createConfigTable() {
        return new Config.Table();
    }

    /**
     * Create an instance of {@link Config.Files }
     * 
     */
    public Config.Files createConfigFiles() {
        return new Config.Files();
    }

    /**
     * Create an instance of {@link Config.Table.Subtable }
     * 
     */
    public Config.Table.Subtable createConfigTableSubtable() {
        return new Config.Table.Subtable();
    }

    /**
     * Create an instance of {@link Config.GenAll }
     * 
     */
    public Config.GenAll createConfigGenAll() {
        return new Config.GenAll();
    }

    /**
     * Create an instance of {@link Config.Variables }
     * 
     */
    public Config.Variables createConfigVariables() {
        return new Config.Variables();
    }

    /**
     * Create an instance of {@link Config.Templates.Template }
     * 
     */
    public Config.Templates.Template createConfigTemplatesTemplate() {
        return new Config.Templates.Template();
    }

    /**
     * Create an instance of {@link Config.Templates }
     * 
     */
    public Config.Templates createConfigTemplates() {
        return new Config.Templates();
    }

    /**
     * Create an instance of {@link Config.Table.Variable }
     * 
     */
    public Config.Table.Variable createConfigTableVariable() {
        return new Config.Table.Variable();
    }

}
