//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.07 at 03:20:32 ���� CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.raise.com/generator/code")
package com.raise.generator.mode;
